backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "list", field: {label: "author", name: "Author", widget: "string"} }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}", date_format: "YYYY-MM-DD", picker_utc: false }
      - { label: "Format", name: "format", widget: "string", required: false }
      - { label: "Topics", name: "topics", widget: "list", field: {label: "topic", name: "Topic", widget: "string"} }
      - { label: "Source", name: "source", widget: "string", required: false }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "template", name: "layout", widget: "hidden", default: "article.html" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "opinion" # Used in routes, e.g., /admin/collections/blog
    label: "Opinion" # Used in the UI
    folder: "content/opinion" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "list", field: {label: "author", name: "Author", widget: "string"} }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}", date_format: "YYYY-MM-DD", picker_utc: false }
      - { label: "Format", name: "format", widget: "string", required: false }
      - { label: "Topics", name: "topics", widget: "list", field: {label: "topic", name: "Topic", widget: "string"} }
      - { label: "Source", name: "source", widget: "string", required: false }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "template", name: "layout", widget: "hidden", default: "article.html" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "longform" # Used in routes, e.g., /admin/collections/blog
    label: "Longform" # Used in the UI
    folder: "content/longform" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "list", field: {label: "author", name: "Author", widget: "string"} }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}", date_format: "YYYY-MM-DD", picker_utc: false }
      - { label: "Format", name: "format", widget: "string", required: false }
      - { label: "Topics", name: "topics", widget: "list", field: {label: "topic", name: "Topic", widget: "string"} }
      - { label: "Source", name: "source", widget: "string", required: false }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "template", name: "layout", widget: "hidden", default: "article.html" }
      - { label: "Body", name: "body", widget: "markdown" }
